API for product of 2 numbers
---
tags:
  - Performing calculations on two numnbers
parameters:
  - name: numbers_to_multiply
    in: body
    schema:
      type: object
      properties:
       n3:
        type: string
       n4:
        type: string
responses:
  500:
   description: Internal Server Error.
  200:
   description: Product of 2 numbers.